demo/config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root   'staticpages#home'
  get    '/help',    to: 'staticpages#help'
  get    '/about',   to: 'staticpages#about'
  get    '/contact', to: 'staticpages#contact'
#  get    '/signup',  to: 'users#new'
  get    '/signup_1',  to: 'people#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post    '/signup_1',  to: 'people#create'
   get 'microposts/index', to: 'microposts#index'
   get 'page/:id' => 'microposts#page', :as => 'page'
     get  'people/ranking'

     mount ActionCable.server => '/cable'

  resources :people do
    member do
      get :requestlist, :receivelist
    end
  end

  resources :microposts do
    resources :comments, :only => [:create, :destroy]
  end

#  resources :users
  resources :people
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :update]
  resources :relationships,       only: [:create, :destroy, :update]
end

demo/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

demo/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

demo/app/views/shared/_info.html.erb
<div class="personinfo">
<ul>
<% if @user.sex == false %>
<li> gender: male </li>
<% else %>
<li> gender: female </li>
<% end %>
<% if @user.syear <= 0 %>
<li> professor </li>
<% else %>
<li> grade: <%= @user.syear %> </li>
<% end %>
<li> birth place: <%= @user.bplace %> </li>

<% if current_person.relationshipsA.find_by(personB_id: @user.id).nil? %>
<% else %>
  <% if current_person.relationshipsA.find_by(personB_id: @user.id).disclosure == 1 %>
    <li> email: <%= @user.email %> </li>
    <li> telnumber: <%= @user.tel %> </li>
  <% elsif current_person.relationshipsA.find_by(personB_id: @user.id).disclosure == 2 %>
    <% if current_person.relationshipsA.find_by(personB_id: @user.id).value >= 45 %>
      <li> email: <%= @user.email %> </li>
    <% else %>
    <% end %>
    <% if current_person.relationshipsA.find_by(personB_id: @user.id).value >= 60 %>
      <li> telnumber: <%= @user.tel %> </li>
    <% else %>
    <% end %>
  <% else %>
  <% end %>
<% end %>

<% if current_person.relationshipsB.find_by(personA_id: @user.id).nil? %>
<% else %>
  <% if current_person.relationshipsB.find_by(personA_id: @user.id).disclosure == 1 %>
    <li> email: <%= @user.email %> </li>
    <li> telnumber: <%= @user.tel %> </li>
  <% elsif current_person.relationshipsB.find_by(personA_id: @user.id).disclosure == 2 %>
    <% if current_person.relationshipsB.find_by(personA_id: @user.id).value >= 45 %>
      <li> email: <%= @user.email %> </li>
    <% else %>
    <% end %>
    <% if current_person.relationshipsB.find_by(personA_id: @user.id).value >= 60 %>
      <li> telnumber: <%= @user.tel %> </li>
    <% else %>
    <% end %>
  <% else %>
  <% end %>
<% end %>

<% if current_person?(@user) %>
  <li> email: <%= @user.email %> </li>
  <li> telnumber: <%= @user.tel %> </li>
<% else %>
<% end %>
</ul>
</div>

demo/app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

demo/app/views/shared/_name.html.erb
<% if current_person.relationshipsA.find_by(personB_id: @user.id).nil? %>
<% elsif current_person.relationshipsA.find_by(personB_id: @user.id).disclosure == 1 || \
         current_person.relationshipsA.find_by(personB_id: @user.id).disclosure == 2 %>
<%= @user.name %>
<% else %>
<%= @user.handlename %>
<% end %>
<% if current_person.relationshipsB.find_by(personA_id: @user.id).nil? %>
<% elsif current_person.relationshipsB.find_by(personA_id: @user.id).disclosure == 1 || \
         current_person.relationshipsB.find_by(personA_id: @user.id).disclosure == 2 %>
<%= @user.name %>
<% else %>
<%= @user.handlename %>
<% end %>
<% if current_person.relationshipsA.find_by(personB_id: @user.id).nil? && \
  current_person.relationshipsB.find_by(personA_id: @user.id).nil? %>
<%= @user.handlename %>
<% else %>
<% end %>

demo/app/views/shared/_person_info.html.erb
<%= link_to gravatar_for(current_person, size: 50), current_person %>
<h1><%= current_person.handlename %></h1>
<span><%= link_to "view my profile", current_person %></span>
<span><%= pluralize(current_person.microposts.count, "micropost") %></span>

demo/app/views/shared/_stats.html.erb
<% @user ||= current_person %>
<div class="stats">
  <a href="<%= requestlist_person_path(@user) %>">
    <strong id="kankei" class="stat">
      <%= @user.kankeiA.where("value > ? and sendA = ? and sendB = ? and waitA = ? and waitB = ?", 30, false, false, false, false ).count \
      + @user.kankeiB.where("value > ? and sendA = ? and sendB = ? and waitA = ? and waitB = ?", 30, false, false, false, false ).count %>
    </strong>
    possible to send request
  </a>
  <a href="<%= receivelist_person_path(@user) %>">
    <strong id="kankei" class="stat">
      <%= @user.kankeiA.where("sendB = ? and waitB = ? and disclosure = ?", true, true, 0).count \
      + @user.kankeiB.where("sendA = ? and waitA = ? and disclosure = ?", true, true, 0).count %>
    </strong>
    receive request
  </a>
</div>

demo/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>