demo/config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  root   'staticpages#home'
  get    '/help',    to: 'staticpages#help'
  get    '/about',   to: 'staticpages#about'
  get    '/contact', to: 'staticpages#contact'
#  get    '/signup',  to: 'users#new'
  get    '/signup_1',  to: 'people#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post    '/signup_1',  to: 'people#create'
   get 'microposts/index', to: 'microposts#index'
   get 'page/:id' => 'microposts#page', :as => 'page'
     get  'people/ranking'

     mount ActionCable.server => '/cable'

  resources :people do
    member do
      get :requestlist, :receivelist
    end
  end

  resources :microposts do
    resources :comments, :only => [:create, :destroy]
  end

#  resources :users
  resources :people
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :update]
  resources :relationships,       only: [:create, :destroy, :update]
end

demo/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :person
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :person_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

  private

    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

demo/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_person, only: [:create, :destroy]
  before_action :correct_person,   only: :destroy

  def create
    @micropost = current_person.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      @geter = current_person
      po = current_person.point
      if current_person.syear <= 0
        tw = 1.5
      else
        tw = 1.0
      end
        po = po + 10*tw
      @geter.update_attribute( :point, po )
      redirect_to root_url
    else
      @feed_items = []
      render 'staticpages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

def update
  if current_person.count >= 5
    else
      @geter = current_person
      po = current_person.point
      po = po + 5
      co = current_person.count
      co += 1
      @geter.update_attribute(:point, po)
      @geter.update_attribute(:count, co)
    end
end

   def index
     @articles = Micropost.all
   end

  def page
    @article = Micropost.find(params[:id])
    @comment = Comment.new
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_person
      @micropost = current_person.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

demo/app/helpers/microposts_helper.rb
module MicropostsHelper
end

demo/app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.person, size: 50), micropost.person %>
  <span class="person"><%= link_to micropost.person.handlename, micropost.person %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    comments（<%= micropost.comments.count %>）
    <br>
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_person?(micropost.person) %>
    <%= link_to "delete", micropost, method: :delete,
    data: { confirm: "You sure?" } %>
    <% end %>
    <h4 ><%= link_to "more details", page_path(micropost) %></h4>
  </span>
</li>

demo/app/views/microposts/index.html.erb
<% @articles.each do |micropost| %>
  <div style="width:500px;border:1px solid #ccc;margin:5px">
    <div style="float:left">
      <h2 ><%= micropost.id %></h2>
    </div>
    <div style="clear:both">
      <pre><%= micropost.content %></pre>
    </div>
  </div>
<% end %>

demo/app/views/microposts/page.html.erb
<div style="float:left">
  <h3 >Question </h3>
</div>
<div style="clear:both">
  <%= @article.content %>
</div>
<p><%= button_to "Agreeing", micropost_path, method: :patch %></p>

<h3>comments：</h3>
<% @article.comments.each do |comment| %>
<h5> from <%= comment.from %></h5>
<pre><%= comment.body %></pre>
<% if logged_in? && comment.from == current_person.handlename %>
<p>[<%= link_to 'reject comments',  [@article, comment],
confirm: 'Are you sure?', method: :delete %>]</p>
<% end %>
<% end %>
<h3>add comments：</h3>
<%= form_for [@article, @comment] do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.hidden_field :from, :value => current_person.handlename, class: 'form-control' %>
<p>comment:</p><p><%= f.text_area :body, :rows => 5, class: 'form-control' %></p>
<%= f.submit 'post comments' %>
<% end %>